version: '4'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: template-database
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - template-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      STAGE: ${STAGE}
      API_PREFIX: ${API_PREFIX}
      DATABASE_URL: ${DATABASE_URL}
    container_name: template-api
    networks:
      - template-network
    depends_on:
      - db

networks:
  template-network:
    driver: bridge