version: '4'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: template-database
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - template-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      STAGE: ${STAGE}
      API_PREFIX: ${API_PREFIX}
      DATABASE_URL: ${DATABASE_URL}
    container_name: template-api
    networks:
      - template-network
    depends_on:
      - db
      - mongo
    restart: always
    
  queue:
    image: rabbitmq:3-management-alpine
    container_name: 'queue'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - template-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    container_name: template-mongo
    volumes:
      - ./mongo:/data/db
    networks:
      - template-network

networks:
  template-network:
    driver: bridge