"""shopping cart

Revision ID: 65b992f47e74
Revises: 9c5b40174302
Create Date: 2025-01-02 13:31:19.636804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65b992f47e74'
down_revision: Union[str, None] = '9c5b40174302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'shopping_cart',
        sa.Column('product_id', sa.String, nullable=False),
        sa.Column('user_id', sa.String, nullable=False),
        sa.Column('quantity', sa.Integer, nullable=False),
        sa.Column('created_at',sa.DateTime, nullable=False),
        sa.Column('updated_at',sa.DateTime, nullable=True),
    )
    op.create_foreign_key(
        'product_shopping_cart_fk',
        'shopping_cart',
        'products',
        ['product_id'],
        ['id'],
    )
    op.create_foreign_key(
        'user_shopping_cart_fk',
        'shopping_cart',
        'users',
        ['user_id'],
        ['id'],
    )
    op.create_primary_key(
        'shopping_cart_pk',
        'shopping_cart',
        ['product_id','user_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_cart')
    # ### end Alembic commands ###
