"""inventory

Revision ID: 9c5b40174302
Revises: d0372fa77904
Create Date: 2024-12-28 17:03:51.647270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5b40174302'
down_revision: Union[str, None] = 'd0372fa77904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.String, primary_key=True),
    sa.Column('product_id', sa.String, nullable=False),
    sa.Column('stock', sa.Integer, nullable=False),
    )
    
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
   
    # ### end Alembic commands ###
