"""Increased size for User Password

Revision ID: d0372fa77904
Revises: 3065b0448789
Create Date: 2024-11-28 21:58:11.920067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0372fa77904'
down_revision: Union[str, None] = '3065b0448789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name="users", column_name="password",type_=sa.String(100))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name="users", column_name="password",type_=sa.String(50))
    # ### end Alembic commands ###
